### ISSUE TITLE
Duktape shouldn't use `log2` on Android even with C99 detected

### ISSUE THREAD

**Issue by HouQiming** [svaarala/duktape#1325]
After updating duktape to 2.0, we started getting build failures on Android:
`duk_bi_math.c:120: error: undefined reference to 'log2'`

Our projects are built with `-std=c99`, but googling indicates that Android doesn't support log2 regardless of the chosen C standard:
http://stackoverflow.com/questions/11080118/does-android-support-log2

As a quick hack, I updated the `#if` around the `log2` stuff to:
`#if (defined(DUK_F_C99) || defined(DUK_F_CPP11) || (defined(_MSC_VER) && (_MSC_VER >= 1800))) && !(defined(ANDROID)||defined(__ANDROID__))`

Everything works after that.

**Comment by svaarala** [comment]
@HouQiming Thanks, this should be easy to resolve. I'll ping back when a fix pull is available for testing.
